# Generated by Django 5.2.4 on 2025-09-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_editora_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='editora',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
