# Generated by Django 5.2.4 on 2025-09-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_editora_editora_alter_livro_desconto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='editora',
            field=models.CharField(max_length=100),
        ),
    ]
