# Generated by Django 5.2.4 on 2025-09-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_editora_editora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='editora',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
